### ISSUE TITLE
Batbot does not work after updating the API

### ISSUE THREAD

**Issue by rauhmaru** [theMiddleBlue/BaTbot#2]
After the API update to 2.0, apparently the command execution has been stopped. I wonder if really this was the cause. Before work fully, but this last week does not work anymore. Thank you.

**Comment by theMiddleBlue** [comment]
hi,

thanks for the update, i will check as soon as possible :)

**Comment by rauhmaru** [comment]
Thank you!
I did a project using the batbot, for scripting and queries to our monitoring system (Zabbix). It was excellent, but there was this problem :(

**Comment by theMiddleBlue** [comment]
Hi @rauhmaru 

there was a problem on the regular expression that parse the "text message" parameter. I've pushed a new version of BatBot that seems to work with the new Telegram API.

can you check?

thank you very much for your contribute :)

-theMiddle

**Comment by rauhmaru** [comment]
Working perfectly! Thanks a lot!
