### ISSUE TITLE
No utf-8 support

### ISSUE THREAD

**Issue by Madji** [theMiddleBlue/BaTbot#3]
#Hello it simle and fine bot. But does not support user names in utf-8. Help how to fix it?
Thanks for you work.

**Comment by theMiddleBlue** [comment]
Hi @Madji 

thank you! i think I've fixed it: Could you please try with the new version?

<img width="337" alt="schermata 2016-09-06 alle 10 04 50" src="https://cloud.githubusercontent.com/assets/4454961/18266152/8715fbb0-7419-11e6-94b9-28aaa0bfb5c2.png">

**Comment by Madji** [comment]
Thanks. username fixed. 
Have you thought to alter the parsing of the messages ? To support utf -8 ? It would be just fine. I know complicated code. but you can use third-party libraries. I myself am not a programmer and do not understand this. But anyway, thank you for the work. Maxim
This answer bot fo me ))))))


Hi \u041c\u0430\u043a\u0441\u0438\u043c, pleased to meet you :)
