### ISSUE TITLE
Bug for all comands boot, run only \\/uptime 

### ISSUE THREAD

**Issue by willf5** [theMiddleBlue/BaTbot#7]
Hi, 

Boot only run comands on "\\/" not run comand in "/"

**Comment by theMiddleBlue** [comment]
Hi @willf5 

thanks for your report! i think i've fixed this issue. Can you try again?

thanks,
bye!

-theMiddle

**Comment by willf5** [comment]
Hi @theMiddleBlue solved!

Thanks.
